# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            RoughBook
tagline:          'An intelligent polls offering'
description:      'The best place to stay up-to-date with the latest RoughBook news and events.'
url:              https://blog.roughbook.xyz

author:
  name:           'Roughbook'
  url:            https://twitter.com/@roughbook_xyz

paginate:         5

# Custom vars
version:          1.0.0

careers:
  url:           https://angel.co/roughbook/jobs
